using System;
using System.Collections.Generic;
using System.Linq;

public static class ChallengeRuns
{
	public static Dictionary<Type, Type> ItemUnlocks = new Dictionary<Type, Type>
	{
		{
			typeof(SupplyAndDemand),
			typeof(MirrorBall)
		},
		{
			typeof(DecisionParalysis),
			typeof(HeadTrauma)
		},
		{
			typeof(Sudoku),
			typeof(BusySchedule)
		},
		{
			typeof(UpAndUp),
			typeof(NumberGoUp)
		},
		{
			typeof(SecretSanta),
			typeof(MysteryGift)
		},
		{
			typeof(MunchTime),
			typeof(HungryHippo)
		},
		{
			typeof(Antiphilatelist),
			typeof(BarOfSoap)
		},
		{
			typeof(Masochist),
			typeof(Honeypot)
		},
		{
			typeof(CallOfTheVoid),
			typeof(Ruler)
		},
		{
			typeof(Chromaphilia),
			typeof(ChristmasTree)
		},
		{
			typeof(Chromaphobia),
			typeof(Sushi)
		},
		{
			typeof(TwoWrongs),
			typeof(Ambulance)
		},
		{
			typeof(Bullseye),
			typeof(Dartboard)
		},
		{
			typeof(SicilianDefense),
			typeof(EightBall)
		},
		{
			typeof(TheBonesRound),
			typeof(WindChime)
		},
		{
			typeof(Cursophobia),
			typeof(JuiceBox)
		},
		{
			typeof(Lexographer),
			typeof(MichaelsBook)
		},
		{
			typeof(InTheBeginning),
			typeof(Chick)
		},
		{
			typeof(RedLetterDay),
			typeof(SpicyPepper)
		},
		{
			typeof(RedPepperDay),
			typeof(Rosebud)
		},
		{
			typeof(EmptyGrid),
			typeof(LuffingJibCrane)
		},
		{
			typeof(DoNotPassGo),
			typeof(FutureFunds)
		},
		{
			typeof(Embargo),
			typeof(Eraser)
		},
		{
			typeof(PlayingFavourites),
			typeof(BaseCamp)
		},
		{
			typeof(ColourSwap),
			typeof(CanOfBeans)
		},
		{
			typeof(SpeedrunChallenge),
			null
		}
	};

	public static Dictionary<Type, string> ChallengeSteamAchievementNames = new Dictionary<Type, string>
	{
		{
			typeof(SupplyAndDemand),
			"ACH_SUPPLY_AND_DEMAND"
		},
		{
			typeof(DecisionParalysis),
			"ACH_DECISION_PARALYSIS"
		},
		{
			typeof(Sudoku),
			"ACH_ADVENT_CALENDAR"
		},
		{
			typeof(UpAndUp),
			"ACH_UP_AND_UP"
		},
		{
			typeof(SecretSanta),
			"ACH_SECRET_SANTA"
		},
		{
			typeof(MunchTime),
			"ACH_MUNCH_TIME"
		},
		{
			typeof(Antiphilatelist),
			"ACH_ANTIPHILATELIST"
		},
		{
			typeof(Masochist),
			"ACH_MASOCHIST"
		},
		{
			typeof(CallOfTheVoid),
			"ACH_CALL_OF_THE_VOID"
		},
		{
			typeof(Chromaphilia),
			"ACH_CHROMAPHILIA"
		},
		{
			typeof(Chromaphobia),
			"ACH_CHROMAPHOBIA"
		},
		{
			typeof(TwoWrongs),
			"ACH_TWO_WRONGS"
		},
		{
			typeof(Bullseye),
			"ACH_BULLSEYE"
		},
		{
			typeof(SicilianDefense),
			"ACH_KNIGHT_TIME"
		},
		{
			typeof(TheBonesRound),
			"ACH_THE_BONES_ROUND"
		},
		{
			typeof(Cursophobia),
			"ACH_CURSOPHOBIA"
		},
		{
			typeof(Lexographer),
			"ACH_LEXOGRAPHER"
		},
		{
			typeof(InTheBeginning),
			"ACH_IN_THE_BEGINNING"
		},
		{
			typeof(RedLetterDay),
			"ACH_RED_LETTER_DAY"
		},
		{
			typeof(RedPepperDay),
			"ACH_RED_PEPPER_DAY"
		},
		{
			typeof(EmptyGrid),
			"ACH_EMPTY_GRID"
		},
		{
			typeof(DoNotPassGo),
			"ACH_DO_NOT_PASS_GO"
		},
		{
			typeof(Embargo),
			"ACH_EMBARGO"
		},
		{
			typeof(PlayingFavourites),
			"ACH_PLAYING_FAVOURITES"
		},
		{
			typeof(ColourSwap),
			"ACH_CHROMATIC_ABERRATION"
		},
		{
			typeof(SpeedrunChallenge),
			"ACH_WERE_FINALLY_LANDING"
		}
	};

	public static Type GetChallengeRunByUnlockItem(Item item)
	{
		return ItemUnlocks.FirstOrDefault((KeyValuePair<Type, Type> kvp) => item.GetType() == kvp.Value).Key;
	}

	public static int GetChallengeRunIndex(ChallengeRun challengeRun)
	{
		return ItemUnlocks.Keys.ToList().IndexOf(challengeRun.GetType()) + 1;
	}

	public static Type GetChallengeRunAtIndex(int index)
	{
		return ItemUnlocks.Values.ToList()[index];
	}
}
