"""Auto-generated regression tests from scoring_mismatches/*.json.

Append cases with:
  python scripts/mismatch_to_test.py path/to/mismatch.json
"""

def test_mismatch_20260523_050326():
    """Regression from mismatch {}."""
    from cursed_words_solver.loadout import parse_board_from_run_state, parse_run_state
    from cursed_words_solver.rules.pipeline import ScoringPipeline

    run_state = {
    "character": "Nina Nix",
    "pin_branch": "",
    "money": 0,
    "stickers": [
        {
            "id": "game_pad",
            "name": "Game Pad",
            "level": 3,
            "kind": "sticker"
        },
        {
            "id": "ten_pin_bowling",
            "name": "Ten Pin Bowling",
            "level": 2,
            "kind": "sticker"
        },
        {
            "id": "artist_s_palette",
            "name": "Artist's Palette",
            "level": 3,
            "kind": "sticker"
        },
        {
            "id": "fish_cake",
            "name": "Fish Cake",
            "level": 1,
            "kind": "sticker"
        },
        {
            "id": "ornate_key",
            "name": "Ornate Key",
            "level": 3,
            "kind": "sticker"
        }
    ],
    "stamps": [
        {
            "id": "dangerous_summit",
            "name": "Dangerous Summit",
            "level": 1,
            "kind": "sticker"
        },
        {
            "id": "slot_machine",
            "name": "Slot Machine",
            "level": 1,
            "kind": "sticker"
        },
        {
            "id": "hungry_snake",
            "name": "Hungry Snake",
            "level": 1,
            "kind": "sticker"
        },
        {
            "id": "flamingo",
            "name": "Flamingo",
            "level": 1,
            "kind": "sticker"
        }
    ],
    "boss_id": "bossdino",
    "boss_name": "Cretaceous Meg",
    "boss_effect": "",
    "extras": {
        "boss_area_number": "5",
        "pin_effect": "milky_way",
        "pin_left_level": "3",
        "pin_right_level": "3",
        "pin_memory": "[]",
        "cards_submitted": "0"
    },
    "board": {
        "source": "melmod",
        "row_order": "top_first",
        "money": 0,
        "rows": 5,
        "cols": 5,
        "tiles": [
            {
                "row": 4,
                "col": 0,
                "char": "r",
                "letter": "R",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 4,
                "col": 1,
                "char": "d",
                "letter": "D",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 4,
                "col": 2,
                "char": "e",
                "letter": "E",
                "base_score": 1.0,
                "color": "colorless",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 4,
                "col": 3,
                "char": "u",
                "letter": "U",
                "base_score": 1.0,
                "color": "colorless",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 4,
                "col": 4,
                "char": "l",
                "letter": "L",
                "base_score": 2.0,
                "color": "red",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 3,
                "col": 0,
                "char": "5",
                "letter": "5",
                "base_score": 0.0,
                "color": "void",
                "curse": "number",
                "number_value": 5,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 3,
                "col": 1,
                "char": "j",
                "letter": "J",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 3,
                "col": 2,
                "char": "i",
                "letter": "I",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 3,
                "col": 3,
                "char": "o",
                "letter": "O",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 3,
                "col": 4,
                "char": "e",
                "letter": "E",
                "base_score": 2.0,
                "color": "blue",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 2,
                "col": 0,
                "char": "a",
                "letter": "A",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 2,
                "col": 1,
                "char": "6",
                "letter": "6",
                "base_score": 0.0,
                "color": "void",
                "curse": "number",
                "number_value": 6,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 2,
                "col": 2,
                "char": "g",
                "letter": "G",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 2,
                "col": 3,
                "char": "a",
                "letter": "A",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 2,
                "col": 4,
                "char": "r",
                "letter": "R",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 1,
                "col": 0,
                "char": "i",
                "letter": "I",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 1,
                "col": 1,
                "char": "k",
                "letter": "K",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 1,
                "col": 2,
                "char": "7",
                "letter": "7",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "number",
                "number_value": 7,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 1,
                "col": 3,
                "char": "n",
                "letter": "N",
                "base_score": 1.0,
                "color": "colorless",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 1,
                "col": 4,
                "char": "n",
                "letter": "N",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 0,
                "col": 0,
                "char": "l",
                "letter": "L",
                "base_score": 0.0,
                "color": "void",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 0,
                "col": 1,
                "char": "s",
                "letter": "S",
                "base_score": 50.0,
                "color": "shiny",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 0,
                "col": 2,
                "char": "o",
                "letter": "O",
                "base_score": 2.0,
                "color": "red",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 0,
                "col": 3,
                "char": "n",
                "letter": "N",
                "base_score": 2.0,
                "color": "red",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            },
            {
                "row": 0,
                "col": 4,
                "char": "o",
                "letter": "O",
                "base_score": 1.0,
                "color": "colorless",
                "curse": "letter",
                "number_value": None,
                "fraction_value": None,
                "consumable": False,
                "active": True,
                "take": False,
                "card_suit": "",
                "card_rank": ""
            }
        ]
    }
}
    board = parse_board_from_run_state(run_state)
    loadout = parse_run_state(run_state)
    pipeline = ScoringPipeline()
    score, _bd = pipeline.score(board, [6, 10, 14, 18, 12, 11, 7, 1], 'daroghas', loadout)
    assert int(score) == 1815
