#!/usr/bin/env python3
"""Generate docs/game-research/tile-audit.md from tile_enums + taxonomy + solver models."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENUMS = ROOT / "data" / "game" / "tile_enums.json"
TAXONOMY = ROOT / "data" / "game" / "tile_taxonomy.json"
OUT = ROOT / "docs" / "game-research" / "tile-audit.md"


def main() -> int:
    enums = json.loads(ENUMS.read_text(encoding="utf-8")) if ENUMS.is_file() else {}
    tax = json.loads(TAXONOMY.read_text(encoding="utf-8")) if TAXONOMY.is_file() else {}
    game_colors = {e["name"] for e in enums.get("enums", {}).get("TileType", [])}
    game_glyphs = {e["name"] for e in enums.get("enums", {}).get("GlyphType", [])}
    mapped_colors = {c["game_tile_type"] for c in tax.get("colors", [])}
    mapped_glyphs = {c["game_glyph_type"] for c in tax.get("curses", [])}
    unmapped_colors = sorted(game_colors - mapped_colors)
    unmapped_glyphs = sorted(game_glyphs - mapped_glyphs)

    lines = [
        "# Tile audit",
        "",
        "Generated by `python scripts/generate_tile_audit.py`.",
        "",
        "## TileType coverage",
        "",
        "| Game | Solver | Base rule | Hooks |",
        "|------|--------|-----------|-------|",
    ]
    for row in tax.get("colors", []):
        hooks = ", ".join(row.get("scoring_hooks", []) or [])
        lines.append(
            f"| `{row['game_tile_type']}` | `{row['solver_color']}` | "
            f"{row.get('base_score_rule', '')} | {hooks or '—'} |"
        )
    lines.extend(
        [
            "",
            f"**Unmapped TileType:** {', '.join(f'`{x}`' for x in unmapped_colors) or 'none'}",
            "",
            "## GlyphType coverage",
            "",
            "| Game | Melmod | Solver |",
            "|------|--------|--------|",
        ]
    )
    for row in tax.get("curses", []):
        lines.append(
            f"| `{row['game_glyph_type']}` | `{row['melmod_curse']}` | "
            f"`{row['solver_curse']}` |"
        )
    lines.append(
        f"\n**Unmapped GlyphType:** {', '.join(f'`{x}`' for x in unmapped_glyphs) or 'none'}\n"
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    if unmapped_colors or unmapped_glyphs:
        print("WARN: unmapped enums remain", file=__import__("sys").stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
