#!/usr/bin/env python3
"""Generate docs/game-research/pin-audit.md from stickers.json pins bucket."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "wiki" / "stickers.json"
OUT = ROOT / "docs" / "game-research" / "pin-audit.md"


def _track_status(track: dict | None) -> str:
    if not track or not isinstance(track, dict):
        return "—"
    t = track.get("type", "")
    if t in ("scatter_start_grid", "scatter_start_encounter"):
        return "grid_sim"
    if t in ("pin_memory_replay", "human_hands_pin"):
        return "orchestration"
    if t in ("custom", "unmodeled", ""):
        return track.get("effect_class", "custom")
    return "scored"


def main() -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    lines = [
        "# Pin audit",
        "",
        "Generated by `python scripts/generate_pin_audit.py`.",
        "",
        "| Slug | Name | game_class | Left | Right | Legacy type |",
        "|------|------|------------|------|-------|-------------|",
    ]
    for slug, pin in sorted(catalog.get("pins", {}).items()):
        left = pin.get("left") if isinstance(pin.get("left"), dict) else None
        right = pin.get("right") if isinstance(pin.get("right"), dict) else None
        legacy = pin.get("type", "—")
        if left or right:
            legacy = (right or left or {}).get("type", legacy)
        lines.append(
            f"| `{slug}` | {pin.get('name', '')} | {pin.get('game_class', '—')} | "
            f"{_track_status(left)} | {_track_status(right)} | `{legacy}` |"
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
