#!/usr/bin/env python3
"""Generate docs/game-research/sticker-audit.md from stickers.json + game types."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "wiki" / "stickers.json"
GAME_TYPES = ROOT / "data" / "game" / "item_subclasses.json"
OUT = ROOT / "docs" / "game-research" / "sticker-audit.md"


def _status(rule: dict) -> str:
    t = rule.get("type", "")
    if t == "unmodeled":
        return "unmodeled"
    if t in ("custom",) and rule.get("effect_class") in ("scatter", "meta", "movement", "encounter"):
        ec = rule.get("effect_class", "")
        if ec == "scatter":
            return "grid_only"
        if ec == "movement":
            return "search_only"
        return ec or "custom"
    if t.startswith("scatter_"):
        return "grid_sim"
    if t in ("reverse_scoring_order", "shuffle_loadout_order"):
        return "meta_scoring"
    return "scored"


def main() -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    game_names: set[str] = set()
    if GAME_TYPES.is_file():
        data = json.loads(GAME_TYPES.read_text(encoding="utf-8"))
        game_names = {r["name"] for r in data.get("subclasses", [])}

    lines = [
        "# Sticker & stamp audit",
        "",
        "Generated by `python scripts/generate_sticker_audit.py`.",
        "",
        "| Bucket | Slug | Catalog type | Status | game_class |",
        "|--------|------|--------------|--------|------------|",
    ]
    for bucket in ("stickers", "stamps", "pins"):
        for slug, rule in sorted(catalog.get(bucket, {}).items()):
            gc = rule.get("game_class", "")
            if gc and gc not in game_names:
                gc = f"{gc}?"
            lines.append(
                f"| {bucket} | `{slug}` | `{rule.get('type', '')}` | {_status(rule)} | {gc or '—'} |"
            )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
