#!/usr/bin/env python3
"""Generate docs/game-research/boss-audit.md from boss_subclasses + catalog."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUBS = ROOT / "data" / "game" / "boss_subclasses.json"
TAX = ROOT / "data" / "game" / "boss_taxonomy.json"
CATALOG = ROOT / "data" / "wiki" / "stickers.json"
OUT = ROOT / "docs" / "game-research" / "boss-audit.md"

GAME_TO_WIKI = {
    "MaxWordLength": "wolf",
    "MinWordLength": "cobra",
    "ReducedLetterValue": "salamander",
    "NegativeMoney": "robo_monkey",
    "StealsMoney": "fox",
    "BigBoss": "toothed_whale",
    "RandomiseItemOrder": "capybara",
    "ExtraVoids": "mole",
    "ExtraQs": "axolotl",
    "AddNumbers": "bison",
    "DiscolourTiles": "yeti_crab",
    "DestroyGrid": "robo_eel",
    "SmallGrid": "bat",
    "FewerGrids": "badger",
    "ForcedSell": "hyena",
    "CretaceousMegBoss": "cretaceous_meg",
}


def main() -> int:
    subs = json.loads(SUBS.read_text(encoding="utf-8")) if SUBS.is_file() else {}
    tax = json.loads(TAX.read_text(encoding="utf-8")) if TAX.is_file() else {}
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    bosses = catalog.get("bosses", {})
    tax_map = tax.get("bosses", {})

    lines = [
        "# Boss audit",
        "",
        "Generated by `python scripts/generate_boss_audit.py`.",
        "",
        "## Main bosses (16)",
        "",
        "| Slug | game_class | Catalog type | effect_class | grid_handler | Status |",
        "|------|------------|--------------|--------------|--------------|--------|",
    ]
    unmapped_subs: list[str] = []
    for row in subs.get("subclasses", []):
        name = row["name"]
        if name in ("MichaelBoss", "SandySaguaroBoss", "PrismaticBeanBoss", "HumanBoyBoss"):
            continue
        wiki = GAME_TO_WIKI.get(name, "")
        if not wiki:
            unmapped_subs.append(name)
    for slug in sorted(bosses.keys()):
        rule = bosses[slug]
        t = tax_map.get(slug, {})
        gc = t.get("game_class") or rule.get("game_class", "—")
        ec = t.get("effect_class") or rule.get("effect_class", "—")
        gh = t.get("grid_handler") or rule.get("grid_handler", "—")
        ctype = rule.get("type", "")
        if ctype == "custom" and gh != "—":
            status = "grid_sim"
        elif ctype.startswith("boss_") or ctype == "shuffle_loadout_order":
            status = "scored"
        elif ec == "search_only":
            status = "search"
        elif ec == "encounter" and slug == "hyena":
            status = "search_block"
        elif ec == "meta":
            status = "meta"
        else:
            status = "verify"
        lines.append(
            f"| `{slug}` | {gc} | `{ctype}` | {ec} | {gh} | {status} |"
        )
    lines.extend(
        [
            "",
            "## Unmapped BossModifier subclasses",
            "",
            ", ".join(f"`{n}`" for n in unmapped_subs) or "none",
            "",
        ]
    )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 1 if unmapped_subs else 0


if __name__ == "__main__":
    raise SystemExit(main())
