#!/usr/bin/env python3
"""Generate docs/game-research/stamp-audit.md from stickers.json stamps bucket."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "wiki" / "stickers.json"
GAME_STAMPS = ROOT / "data" / "game" / "stamp_subclasses.json"
OUT = ROOT / "docs" / "game-research" / "stamp-audit.md"

SCORING_INACTIVE = frozenset({"unmodeled", "custom", ""})
GRID_TYPES = frozenset({"scatter_start_grid", "scatter_start_encounter"})
META_SCORING = frozenset({"reverse_scoring_order", "shuffle_loadout_order"})
ORCHESTRATION = frozenset({"frankenstein_stitch", "overhand_replay"})


def _status(rule: dict) -> str:
    t = rule.get("type", "")
    ec = rule.get("effect_class", "")
    if t in ORCHESTRATION:
        return "orchestration"
    if t in META_SCORING:
        return "meta_scoring"
    if ec in ("shop", "sell", "sell_cost", "meta") or (
        t == "custom" and ec in ("shop", "sell", "meta", "encounter")
    ):
        if ec == "encounter" or "ENCOUNTER" in str(rule.get("wiki_effect", "")).upper():
            return "encounter"
        return "shop_meta"
    if ec == "movement" or (t == "custom" and ec == "movement"):
        return "search_only"
    if t in GRID_TYPES or (t == "custom" and ec == "scatter"):
        return "grid_sim"
    if t in SCORING_INACTIVE and ec not in ("scatter", "movement"):
        if ec:
            return ec
        return "unmodeled"
    if t and t not in SCORING_INACTIVE:
        return "scored"
    if ec == "scatter":
        return "grid_sim"
    return "verify"


def main() -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    game_map: dict[str, str] = {}
    if GAME_STAMPS.is_file():
        data = json.loads(GAME_STAMPS.read_text(encoding="utf-8"))
        for row in data.get("stamps", []):
            game_map[row["slug"]] = row.get("game_class", "")

    lines = [
        "# Stamp audit",
        "",
        "Generated by `python scripts/generate_stamp_audit.py`.",
        "",
        "| Slug | Name | game_class | Catalog type | Status |",
        "|------|------|------------|--------------|--------|",
    ]
    for slug, rule in sorted(catalog.get("stamps", {}).items()):
        gc = rule.get("game_class") or game_map.get(slug, "—")
        lines.append(
            f"| `{slug}` | {rule.get('name', '')} | {gc or '—'} | "
            f"`{rule.get('type', '')}` | {_status(rule)} |"
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
